---
services:
  hbd-db:
    image: postgres:16.3-bookworm
    container_name: hbd-db
    volumes:
      - hbd-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6684:5432"

  hbd:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hbd
    ports:
      - "8417:8417"
      - "8418:8418"
    depends_on:
      - hbd-db
    environment:
      - DB_TYPE=postgres
      - DATABASE_URL=postgres://postgres:postgres@hbd-db:5432/postgres?sslmode=disable
      - MASTER_KEY=35e150e7ca83247f18cb1a37d61d8e161dddec06027f5db009b34da48c25f1b5
      - PORT=8418
      - ENVIRONMENT=production
      - CUSTOM_DOMAIN=https://hbd.lotiguere.com

networks:
  default:
    name: hbd-network

volumes:
  hbd-data:
    driver: local
