definitions:
  structs.BirthdayFull:
    properties:
      date:
        example: "2021-01-01"
        type: string
      id:
        example: 1
        type: integer
      name:
        example: John Doe
        type: string
    type: object
  structs.BirthdayNameDateAdd:
    properties:
      auth:
        $ref: '#/definitions/structs.LoginRequest'
      date:
        example: "2021-01-01"
        type: string
      name:
        example: John Doe
        type: string
    required:
    - auth
    - date
    - name
    type: object
  structs.BirthdayNameDateModify:
    properties:
      auth:
        $ref: '#/definitions/structs.LoginRequest'
      date:
        example: "2021-01-01"
        type: string
      id:
        example: 1
        type: integer
      name:
        example: John Doe
        type: string
    required:
    - auth
    - date
    - id
    - name
    type: object
  structs.EncryptionKey:
    properties:
      encryption_key:
        example: 9cc76406913372c2b3a3474e8ebb8dc917bdb9c4a7c5e98c639ed20f5bcf4da1
        type: string
    type: object
  structs.Error:
    properties:
      error:
        type: string
    type: object
  structs.LoginRequest:
    properties:
      email:
        example: example@hbd.wtf
        type: string
      encryption_key:
        example: 9cc76406913372c2b3a3474e8ebb8dc917bdb9c4a7c5e98c639ed20f5bcf4da1
        type: string
    required:
    - email
    - encryption_key
    type: object
  structs.LoginSuccess:
    properties:
      birthdays:
        items:
          $ref: '#/definitions/structs.BirthdayFull'
        type: array
      reminder_time:
        example: "15:04"
        type: string
      telegram_bot_api_key:
        example: 270485614:AAHfiqksKZ8WmR2zSjiQ7jd8Eud81ggE3e-3
        type: string
      telegram_user_id:
        example: "123456789"
        type: string
      timezone:
        example: America/New_York
        type: string
    type: object
  structs.ModifyUserRequest:
    properties:
      auth:
        $ref: '#/definitions/structs.LoginRequest'
      new_email:
        example: example2@hbd.wtf
        type: string
      new_reminder_time:
        example: "15:04"
        type: string
      new_telegram_bot_api_key:
        example: 270485614:AAHfiqksKZ8WmR2zSjiQ7jd8Eud81ggE3e-3
        type: string
      new_telegram_user_id:
        example: "123456789"
        type: string
      new_timezone:
        example: America/New_York
        type: string
    required:
    - auth
    - new_reminder_time
    - new_telegram_bot_api_key
    - new_telegram_user_id
    - new_timezone
    type: object
  structs.RegisterRequest:
    properties:
      email:
        example: example@hbd.wtf
        type: string
      encryption_key:
        example: 9cc76406913372c2b3a3474e8ebb8dc917bdb9c4a7c5e98c639ed20f5bcf4da1
        type: string
      reminder_time:
        example: "15:04"
        type: string
      telegram_bot_api_key:
        example: 270485614:AAHfiqksKZ8WmR2zSjiQ7jd8Eud81ggE3e-3
        type: string
      telegram_user_id:
        example: "123456789"
        type: string
      timezone:
        example: America/New_York
        type: string
    required:
    - email
    - encryption_key
    - reminder_time
    - telegram_bot_api_key
    - telegram_user_id
    - timezone
    type: object
  structs.Success:
    properties:
      success:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /birthday:
    delete:
      consumes:
      - application/json
      description: This endpoint deletes a birthday for the authenticated user.
      parameters:
      - description: Delete birthday
        in: body
        name: birthday
        required: true
        schema:
          $ref: '#/definitions/structs.BirthdayNameDateModify'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.Success'
        "400":
          description: Invalid date format
          schema:
            $ref: '#/definitions/structs.Error'
        "500":
          description: Failed to delete birthday
          schema:
            $ref: '#/definitions/structs.Error'
      summary: Delete a birthday
      tags:
      - birthdays
      x-order: 8
    post:
      consumes:
      - application/json
      description: This endpoint adds a new birthday for the authenticated user.
      parameters:
      - description: Add birthday
        in: body
        name: birthday
        required: true
        schema:
          $ref: '#/definitions/structs.BirthdayNameDateAdd'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.Success'
        "400":
          description: Invalid date format
          schema:
            $ref: '#/definitions/structs.Error'
        "500":
          description: Failed to insert birthday
          schema:
            $ref: '#/definitions/structs.Error'
      summary: Add a new birthday
      tags:
      - birthdays
      x-order: 7
    put:
      consumes:
      - application/json
      description: This endpoint modifies a birthday for the authenticated user.
      parameters:
      - description: Modify birthday
        in: body
        name: birthday
        required: true
        schema:
          $ref: '#/definitions/structs.BirthdayNameDateModify'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.Success'
        "400":
          description: Invalid date format
          schema:
            $ref: '#/definitions/structs.Error'
        "500":
          description: Failed to commit transaction
          schema:
            $ref: '#/definitions/structs.Error'
      summary: Modify a birthday
      tags:
      - birthdays
      x-order: 9
  /check-birthdays:
    post:
      consumes:
      - application/json
      description: This endpoint checks for user reminders through a POST request.
      parameters:
      - description: Check reminders
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/structs.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.Success'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/structs.Error'
        "500":
          description: Error querying users
          schema:
            $ref: '#/definitions/structs.Error'
      summary: Check user reminders
      tags:
      - reminders
      x-order: 6
  /delete-user:
    delete:
      consumes:
      - application/json
      description: This endpoint deletes a user based on their email and encryption
        key.
      parameters:
      - description: Delete user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/structs.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.Success'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/structs.Error'
        "401":
          description: Invalid encryption key or email
          schema:
            $ref: '#/definitions/structs.Error'
        "500":
          description: Failed to delete user
          schema:
            $ref: '#/definitions/structs.Error'
      summary: Delete a user
      tags:
      - auth
      x-order: 5
  /generate-encryption-key:
    get:
      description: This endpoint generates a new encryption key for the user.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.EncryptionKey'
        "500":
          description: Failed to generate encryption key
          schema:
            $ref: '#/definitions/structs.Error'
      summary: Generate a new encryption key
      tags:
      - auth
      x-order: 1
  /login:
    post:
      consumes:
      - application/json
      description: This endpoint logs in a user by validating their email and encryption
        key.
      parameters:
      - description: Login user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/structs.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.LoginSuccess'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/structs.Error'
        "401":
          description: Invalid encryption key or email
          schema:
            $ref: '#/definitions/structs.Error'
      summary: Login a user
      tags:
      - auth
      x-order: 3
  /modify-user:
    put:
      consumes:
      - application/json
      description: This endpoint modifies a user's details such as Telegram bot API
        key, reminder time, and more.
      parameters:
      - description: Modify user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/structs.ModifyUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.Success'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/structs.Error'
        "401":
          description: Invalid encryption key
          schema:
            $ref: '#/definitions/structs.Error'
        "500":
          description: Failed to update user
          schema:
            $ref: '#/definitions/structs.Error'
      summary: Modify a user's details
      tags:
      - auth
      x-order: 4
  /register:
    post:
      consumes:
      - application/json
      description: This endpoint registers a new user with their email, Telegram bot
        API key, and other details.
      parameters:
      - description: Register user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/structs.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.Success'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/structs.Error'
        "409":
          description: Email or Telegram bot API key already registered
          schema:
            $ref: '#/definitions/structs.Error'
        "500":
          description: Failed to create user
          schema:
            $ref: '#/definitions/structs.Error'
      summary: Register a new user
      tags:
      - auth
      x-order: 2
swagger: "2.0"
